### ISSUE TITLE
Pass inputs in readable format 

### ISSUE THREAD

**Issue by jannisborn** [Pseudomanifold/latex-credits#7]
Could be a game changer in usability to support passing data per concept and in a human-readable form, e.g.,:

```tex
\credit{Conceptualization}{Alice, Bob}
\credit{Data curation}{Charlie}
...
```

**Comment by Pseudomanifold** [comment]
Great idea! We can probably use [`pgfkeys`](https://www.ctan.org/pkg/pgfkeys) for this purpose. Will need a little bit of time to look into, but we can also probably sync on that.

**Comment by jannisborn** [comment]
Finally found some time to work on this 👍🏼  Happy to provide a PR but wanted to discuss here first. The new code can be executed as follows:

```tex
\credit{Alice}{Investigation, Methodology, Data curation, Writing -- original draft}
\credit{Bob}{Visualization,conceptualization}
\credit{Charlie}{Software,Writing -- review \& editing,Validation}

\insertcredits 
\\
\insertcreditsstatement
```

Positive: 
- Intuition: much more intuitive insertion of information (text instead of number)
- Efficiency: Negative information does not have to be provided (via 0), only applicable concepts are given by the user
- Robustness: Order of input concepts can be arbitrary

Negative
- Breaking change because, so far, I did not find a way to still support insertion via the old way (`\credit{Alice}{1,0,1,...}
- Thus: No more support for granular contribution. Contribution is now binary.
- String match has to be exact. E.g., above Bob's field "conceptualization" is lowercase so it does not match the concept name fully. For such cases, the package raises a warning now to the user.

All other package options are still supported 🚀

**Comment by jannisborn** [comment]
Let me know what you think @Pseudomanifold

**Comment by Pseudomanifold** [comment]
Looks very good as an alternative interface, wow! How about we store the old behaviour by providing a new command?

**Comment by jannisborn** [comment]
Cool, agreed that should be easy. We can use:

```tex
% New behavior
\insertcredits 
\insertcreditsstatement

% Old behavior
\insertcreditsgranular
\insertcreditsgranularstatement
```

Will open the PR later today

**Comment by Pseudomanifold** [comment]
Awesome, thanks a lot!
